### ISSUE TITLE
Cannot execute shell scripts with functions

### ISSUE THREAD

**Issue by tejasrao97** [neurobin/shc#103]
#!/bin/bash

total=0
count()
{
for i in $@; do
   if [ ! -z "${i##[0-9]*}" ]; then
        echo "Please enter numeric only"
        exit 1
   fi
   total=$(($total + $i))
done

if [ $total -eq 0 ]; then
    echo "Plesae execute script like: $0 10 20 30"
    exit 0
fi

echo $total

}

count $@

**Comment by neurobin** [comment]
how did you compile?

**Comment by tejasrao97** [comment]
shc -T -f <shell script file name>

**Comment by neurobin** [comment]
use sudo to run the script.
