### ISSUE TITLE
-U, -H options - script won't run as root or user... 

### ISSUE THREAD

**Issue by tmountney** [neurobin/shc#104]
Nice tool... thank you...

If I compile with the '-U' or '-H' options the **binary** won't run; returns error messages:

'-U' option: shc -U -f... -o...
```
program-name: Operation not permitted
Killed
```
'-H' option: shc -H -f... -o...
```
Operation not permitted
Killed
```
Runs without error: shc -f..  -o...

Ideas..? Want to have it somewhat secure from trace or decompile...

Linux Mint 19.3_64, Kernel 5.3.0-51, shc Version 4.0.1

**Comment by neurobin** [comment]
`-U` and `-H` puts extra restriction on the binary. One of them being not runnable with normal user. Try with `sudo`
