### ISSUE TITLE
compile shell script with `*.c` file

### ISSUE THREAD

**Issue by Zacharys-Hackery** [neurobin/shc#106]
I didn't know if this would be possible, but in the process of the shell script being turned into a binary file could the original file be compiled with other `.c` files into the final result?

It seems like the option could just be slipped in the middle of the conversion.

> Shc takes a script, which is specified on the command line and produces **_C source code_**. The generated source code is then compiled and linked to produce a stripped binary executable.

**Comment by ForgivenNin** [comment]
I attempted to try this out myself, noticing that when compiling using `shc`, another file with the extension `*.sh.x.c` is generated, and I got some errors from `clang`. Maybe this could help, because it seems possible to pull off.
[shc-compile-test.zip](https://github.com/neurobin/shc/files/4732371/shc-compile-test.zip)

**Comment by ForgivenNin** [comment]
You still get about the same result if you change the `.cpp` file into a `.c` example.

**Comment by suntong** [comment]
See https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_9.html

I.e., 

`gcc -Wall test.bash.x.c -o test.bash-x`

**Comment by kcubeterm** [comment]
Your shell script  shebang is ```#!/bin/bash```
, Replace it with ```/data/data/com.termux/files/usr/bin/bash```

And when you compile file, it gives *.c file also , 

```
shc -f ./shell.sh -f shell.c
```
Execute it by `./shell.c`

**Comment by kcubeterm** [comment]
*instance*
![IMG_20200621_075731](https://user-images.githubusercontent.com/50498359/85215361-17433180-b395-11ea-8c60-ab9277da8c3b.jpg)

**Comment by Zacharys-Hackery** [comment]
I know that you can compile the bash script into `C`, and I know how the basic compilation works, but I'm asking about including other things, such as external `.c` and header files.

**Comment by neurobin** [comment]
I don't see the use case of doing this. shc creates the .c file which is internal to shc and it already includes all headers that it needs. There is no need for any additional header unless the .c file needs to be changed for some reason. And if the .c file needs to be changed for some reason, then it's the users responsibility to make changes as they wish (which can not be predicted or formulized). Thus it does not seem to be an interesting feature to have.

**Comment by suntong** [comment]
> I don't see the use case of doing this.

Quite agree, doesn't make sense to me at all.
