### ISSUE TITLE
shc generated .c not working under Windows

### ISSUE THREAD

**Issue by suntong** [neurobin/shc#110]
Taking the `test.bash.x.c` file generated by `shc`, and try the following command under different environments,

```
gcc -Wall -O6 -s test.bash.x.c -o test.bash.x
test.bash.x a b c
```

It works OK under Linux:

```
$ test.bash.x a b c
$@ is a b c
command line: test.bash.x a b c
hello world
```

but not OK under Windows. Tried both under 

- Debian under Docker for Windows
- Msys2 

I presume that the `.c` files generated by `shc` is using a very specific Linux function that even within Debian under Docker for Windows is not working, as gcc under all three environments are the same -- `gcc 9.3.0`

Please double-check. thx.

**Comment by neurobin** [comment]
Make use of the `-r` flag of `shc`

**Comment by suntong** [comment]
Perfect! THX!

**Comment by suntong** [comment]
Hold on, it failed again when the script is big. Let me find an example demonstrating that...

**Comment by suntong** [comment]
all good!
