### ISSUE TITLE
Working with `#!/usr/bin/env bash`

### ISSUE THREAD

**Issue by pengyu** [neurobin/shc#111]
It seems that shc does not support the shebang of `#!/usr/bin/env bash`. Could this support be added? Thanks.

**Comment by neurobin** [comment]
Not planned in near future

**Comment by liberize** [comment]
> It seems that shc does not support the shebang of `#!/usr/bin/env bash`. Could this support be added? Thanks.

I wrote an alternate tool, use pipes and support shebang.

https://github.com/liberize/sshc
