### ISSUE TITLE
README out of date, or releases not building right?

### ISSUE THREAD

**Issue by firthmj** [neurobin/shc#112]
Hi,

The "README.rd" file on both the "release" and "master" branches talks about getting binaries from the latest release link.

However, releases after V3.9.6 don't have the binaries included. I'm not sure if the binaries have been dropped after that version, and the README is just out of date, or if there is a build problem that means the binaries are missing

**Comment by neurobin** [comment]
README should be updated as 'download a compiled binary package from release page (if available)'. You can do a pull request if you want. I will not update it for now.

**Comment by neurobin** [comment]
And I probably stopped updating the ubuntu release. It's on Debian now, so the official Ubuntu repository should have the latest releases by default.
