### ISSUE TITLE
ELF not found while Encrypting shell

### ISSUE THREAD

**Issue by msoban54** [neurobin/shc#114]
Sir everytime i am encrypting my shell the compile is completed but when i run .sh.x file it gave me following error
random.sh.x: 1: ELF: not found
random.sh.x: 2: �: not found
random.sh.x: 3: Syntax error: "(" unexpected
tried many fixes and reinstalling but didnt worked, i am using Kali linux.

**Comment by neurobin** [comment]
convert the file to proper UNIX file. use dos2unix.

```
dos2unix file/path
```

**Comment by msoban54** [comment]
Thanks for the reply
i want to ask can i run encrypted shells on my android after compiling from shc?

**Comment by neurobin** [comment]
the shell itself needs to be available. If it was written in `bash`, then it can run wherever `bash` is installed.
