### ISSUE TITLE
aclocal error in Linux version 4.4.13-1-MANJARO

### ISSUE THREAD

**Issue by Yokai-Seishinkage** [neurobin/shc#14]
When running make && make install this error is prioduced in Manjaro 4.4.13.

`[root@yokai shc]# make
 cd . && /bin/sh /root/shc/config/missing automake-1.14 --gnu
/root/shc/config/missing: line 81: automake-1.14: command not found
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:320: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1`

Current version of aclocal is 1.15. Automake is not missing it is just a newer version than in the script.

**Comment by neurobin** [comment]
How about recreating the makefiles (running autogen.sh):

```sh
mkdir m4
./autogen.sh
./configure
make
sudo make install
```

**Comment by Yokai-Seishinkage** [comment]
`[root@yokai shc]# ./autogen.sh
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.`

Tried removing automake 1.15 and using 1.14 like the package tries to find but then I get a message that 1.14 may be too old. 

However, your solution worked even with these errors and so far from what I have seen, teh package is functioning correctly. I'll mark this as solved.
