### ISSUE TITLE
Does reading values from other files slows down execution of shc binary

### ISSUE THREAD

**Issue by syamalach** [neurobin/shc#17]
In my shell script i am reading value from some text file say
`cat /tmp/file` and i am using this value to check condition in shell script and later again i am populating the same file 'echo 1 > /tmp/file'. There is some delay in these performances. After creating shc binary i am seeing performance degrade of my shell script, previously it was fast.Please help me to know is there any limitation with shc

**Comment by neurobin** [comment]
For a detailed talk about the limitation, you can see this:
[http://stackoverflow.com/a/31306270/3744681](http://stackoverflow.com/a/31306270/3744681)
