### ISSUE TITLE
CFLAGS don't work while tring to compile for 32 bit

### ISSUE THREAD

**Issue by mdnasr** [neurobin/shc#18]
I am trying to compile my shell script for 32 bit

    CFLAGS=-m32
    shc -f script -r

Using file command, I got this:

    > file -L script.x
    script.x: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=b4f378e46a4f34301d5dd5fff9f8de1c63d3ad45, stripped

To overcome this problem i compile the source code myself. But i hope that you fix this issue soon

    gcc script.x.c -m32

**Comment by neurobin** [comment]
You are doing it wrong. Run:

```sh
CFLAGS=-m32 shc -f script -r
```
