### ISSUE TITLE
not able to make it run?

### ISSUE THREAD

**Issue by joejoegithub** [neurobin/shc#19]
$ shc -v -U -f mytest.ksh -r
shc shll=ksh
shc [-i]=-c
shc [-x]=exec '%s' "$@"
shc [-l]=
shc opts=-x
shc: cc  mytest.ksh.x.c -o mytest.ksh.x
shc: strip mytest.ksh.x
shc: chmod ug=rwx,o=rx mytest.ksh.x
$ ./mytest.ksh.x 
[1] + Stopped (SIGSTOP)        ./mytest.ksh.x
$  shc -v -f mytest.ksh -r
shc shll=ksh
shc [-i]=-c
shc [-x]=exec '%s' "$@"
shc [-l]=
shc opts=-x
shc: cc  mytest.ksh.x.c -o mytest.ksh.x
shc: strip mytest.ksh.x
shc: chmod ug=rwx,o=rx mytest.ksh.x
--- DBATEST.DEV1@nzrmg@cmcbluntzasrv01-01 /tools/static/nzrmg/tt_tools/REFRESH_production/DBATEST/.SHC/shc-release/test 
$ ./mytest.ksh.x 
./mytest.ksh.x: exec: _9014_./mytest.ksh.x: not found

**Comment by neurobin** [comment]
Try:

```sh
$ shc -v -U -f mytest.ksh -r
$ sudo ./mytest.ksh.x
```

**Comment by neurobin** [comment]
Please open another issue if this problem still persists
