### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by beojan** [neurobin/shc#24]
Perhaps you could make it clear that the purpose of shc is to hide the source code of the shell script rather than to speed up the shell script.

**Comment by neurobin** [comment]
It's pretty much clear if you read the short description carefully.

> The compiled binary will still be dependent on the shell
> ...
> shc itself is not a compiler such as cc, it rather encodes and encrypts a shell script
> ...
> Upon execution, the compiled binary will decrypt and execute the code with the shell -c option.

**Comment by beojan** [comment]
You may want to consider calling it an obfuscator rather than a compiler then.

**Comment by neurobin** [comment]
Makes sense, but the name is historical and technically it does compile (something).
