### ISSUE TITLE
'ePtAttachDeprecated' is deprecated: PT_ATTACH is deprecated. See PT_ATTACHEXC [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by cesariel** [neurobin/shc#25]
../Am.sh.x.c:4703:19: warning: 'ePtAttachDeprecated' is deprecated: PT_ATTACH is deprecated. See PT_ATTACHEXC [-Wdeprecated-declarations]
                        mine = !ptrace(PTRACE_ATTACH, pid, 0, 0);
                                       ^
../Am.sh.x.c:4684:24: note: expanded from macro 'PTRACE_ATTACH'
#       define PTRACE_ATTACH    PT_ATTACH
                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/ptrace.h:85:19: note: expanded from macro 'PT_ATTACH'
#define PT_ATTACH       ePtAttachDeprecated     /* trace some running process */
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/ptrace.h:71:2: note: 'ePtAttachDeprecated' has been explicitly marked deprecated here
        ePtAttachDeprecated __deprecated_enum_msg("PT_ATTACH is deprecated. See PT_ATTACHEXC") = 10
        ^
1 warning generated.

**Comment by BirkhoffLee** [comment]
```
birkhoff at Birkhoff-MBPR in ~/dev/shc (release●)
$ shc -v -r -U -f 123.sh
shc shll=bash
shc [-i]=-c
shc [-x]=exec '%s' "$@"
shc [-l]=
shc opts=
shc: cc  123.sh.x.c -o 123.sh.x
123.sh.x.c:275:19: warning: 'ePtAttachDeprecated' is deprecated: PT_ATTACH is deprecated. See PT_ATTACHEXC [-Wdeprecated-declarations]
                        mine = !ptrace(PTRACE_ATTACH, pid, 0, 0);
                                       ^
123.sh.x.c:256:24: note: expanded from macro 'PTRACE_ATTACH'
#       define PTRACE_ATTACH    PT_ATTACH
                                ^
/usr/include/sys/ptrace.h:85:19: note: expanded from macro 'PT_ATTACH'
#define PT_ATTACH       ePtAttachDeprecated     /* trace some running process */
                        ^
/usr/include/sys/ptrace.h:71:2: note: 'ePtAttachDeprecated' has been explicitly marked deprecated here
        ePtAttachDeprecated __deprecated_enum_msg("PT_ATTACH is deprecated. See PT_ATTACHEXC") = 10
        ^
1 warning generated.
shc: strip 123.sh.x
shc: chmod ug=rwx,o=rx 123.sh.x
```

**Comment by BirkhoffLee** [comment]
It happens only using `-U` to compile. I'm on macOS.
