### ISSUE TITLE
Output created withy -U does not execute at all for non-root users

### ISSUE THREAD

**Issue by PhilipOrleans** [neurobin/shc#29]
if the final result is compiled with -U -f, it fails to execute for any non-root user, which are exactly my users
Operation not permitted

**Comment by neurobin** [comment]
That's how it is from the beginning. I have no intention of changing it (at least now).

**Comment by shayanderson** [comment]
This is unacceptable for most bash scripts in production. If I want to get the version or help/usage of an script I shouldn't have to use root privileges. For example, `myscript --version` or just `myscript` for usage, requiring `sudo myscript --version` is absurd.
