### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by xtay573269555** [neurobin/shc#31]
[oracle@rdbms ~]$ shc -f ora.sh -o ora
[oracle@rdbms ~]$ ./ora tsfree
./ora: Argument list too long: /bin/bash

# cat /etc/issue
CentOS release 6.3 (Final)

**Comment by xtay573269555** [comment]
shc version is 3.9.3

**Comment by neurobin** [comment]
How big your scrip is?

**Comment by xtay573269555** [comment]
The source script is about 270KB，and complied binary script is 290KB。

**Comment by xtay573269555** [comment]
I will print the source code in a moment.

**Comment by xtay573269555** [comment]
#!/bin/bash

export LANG="en_US.UTF-8"
#export LANG="zh_CN.UTF-8"
export NLS_LANG="AMERICAN_AMERICA.AL32UTF8"
export NLS_DATE_FORMAT="yyyy-mm-dd HH24:mi:ss"
export NLS_TIMESTAMP_FORMAT="yyyy-mm-dd HH24:mi:ss.ff"
export NLS_TIMESTAMP_TZ_FORMAT="yyyy-mm-dd HH24:mi:ss.ff TZH:TZM"

if [ "$ORACLE_SID" = "" ]; then
    echo "You MUST set ORACLE_SID first !"
    exit;
fi

IP="==============="
which ifconfig > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    IP=`ifconfig -a | grep inet  | grep -v inet6 | grep -v 127.0.0.1 | head -n 1 | awk '{print $2}' | awk -F ':' '{print $2}'`
else
    IP="==============="
fi

HOSTNAME=`hostname`
DATE=`date '+%F %T'`

SQLPLUS=" sqlplus "
SQLPLUS_HANG=" sqlplus -prelim "
RMAN=" rman "

which sqlplus > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    SQLPLUS=" sqlplus "
else
    echo "Can not find sqlplus !"
    exit;
fi

which rlwrap > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    SQLPLUS=" rlwrap sqlplus "
    SQLPLUS_HANG=" rlwrap sqlplus -prelim "
    RMAN=" rlwrap rman "
else
    SQLPLUS=" sqlplus "
    SQLPLUS_HANG=" sqlplus -prelim "
    RMAN=" rman "
fi

SQLPLUS_PARAM=" / "
RMAN_PARAM=" / ";

if [ "$LOGNAME" = "oracle" ]; then
    SQLPLUS_PARAM=" / as sysdba ";
    RMAN_PARAM=" target / ";
elif [ "$LOGNAME" = "grid" ]; then
    SQLPLUS_PARAM=" / as sysasm ";
    RMAN_PARAM=" target / ";
else
    SQLPLUS_PARAM=" / ";
    RMAN_PARAM=" / ";
    echo "You can not execute this script !"
    exit
fi

SQLPLUS_CMD="$SQLPLUS -S $SQLPLUS_PARAM"
SQLPLUS_HANG_CMD="$SQLPLUS_HANG -S $SQLPLUS_PARAM"
RMAN_CMD="$RMAN $RMAN_PARAM"

SET_LINES_PAGES="SET linesize 200 pagesize 100 long 40000 longc 100000 feedback OFF;"
SET_CURSOR_SHARING="alter session set cursor_sharing=FORCE;"
SET_NLS_DATE_FORMAT="alter session set nls_date_format='YYYY-MM-DD HH24:MI:SS';"
SET_NLS_TIMESTAMP_FORMAT="alter session set nls_timestamp_format = 'YYYY-MM-DD HH24:MI:SS.FF';"
SET_NLS_TIMESTAMP_TZ_FORMAT="alter session set nls_timestamp_tz_format = 'YYYY-MM-DD HH24:MI:SS.FF TZH:TZM';"
SET_GLOGIN="SET time OFF timing OFF head ON feedback ON echo OFF termout ON trimout ON trimspool ON verify OFF serveroutput ON;"

echo  "==========  $DATE  ==========  $HOSTNAME  ==========  $IP  ==========  $ORACLE_SID  =========="

case $1 in 
    tsfree)
        $SQLPLUS_CMD << EOF
        $SET_LINES_PAGES
        $SET_CURSOR_SHARING
        $SET_NLS_DATE_FORMAT
        $SET_NLS_TIMESTAMP_FORMAT
        $SET_NLS_TIMESTAMP_TZ_FORMAT
        $SET_GLOGIN
        column TABLESPACE_NAME format a15
        column SUM_SPACE(M)      format 99999990.99
        column USED_SPACE(M)     format 99999990.99
        column USED_RATE(%)      format 99999990.99
        column FREE_SPACE(M)     format 99999990.99
        column REA_USED_RATE(%)  format 99999990.99
        column REA_FREE_SPACE(M) format 99999990.99
        SELECT d.tablespace_name,
               space "SUM_SPACE(M)",
               space - nvl(free_space, 0) "USED_SPACE(M)",
               round((1 - nvl(free_space, 0) / space) * 100, 2) "USED_RATE(%)",
               free_space "FREE_SPACE(M)",
               CASE
                   WHEN free_space = rea_free_space THEN NULL
                   ELSE round((1 - nvl(rea_free_space, 0) / space) * 100, 2)
               END "REA_USED_RATE(%)",
               CASE
                   WHEN free_space = rea_free_space THEN NULL
                   ELSE rea_free_space
               END "REA_FREE_SPACE(M)"
          FROM (SELECT tablespace_name,
                       round(SUM(bytes) / (1024 * 1024), 2) space
                  FROM dba_data_files
                 GROUP BY tablespace_name) d,
               (SELECT f1.tablespace_name,
                       f1.free_space - nvl(f2.free_space, 0) rea_free_space,
                       f1.free_space
                  FROM (SELECT tablespace_name,
                               round(SUM(bytes) / (1024 * 1024), 2) free_space
                          FROM dba_free_space
                         GROUP BY tablespace_name) f1,
                       (SELECT ts_name tablespace_name,
                               round(SUM(space) * 8 / 1024, 2) free_space
                          FROM dba_recyclebin
                         GROUP BY ts_name) f2
                 WHERE f1.tablespace_name = f2.tablespace_name(+)) f
         WHERE d.tablespace_name = f.tablespace_name(+)
         ORDER BY 1 - nvl(rea_free_space, 0) / space DESC;
        exit
EOF
    ;;

esac

**Comment by neurobin** [comment]
yap, seems like it's exceeds the limitation `_SC_ARG_MAX`
