### ISSUE TITLE
running shc compiled binary in different shell

### ISSUE THREAD

**Issue by sunhwan** [neurobin/shc#36]
I'm having problem running shc compiled binary in a different shell. Here's my simple example shell script. The compiled binary runs fine in bash and zsh, but doesn't produce any output in other shell, such as csh.

```$ cat echo.sh
#!/bin/bash

echo "Hello"
$ shc -f echo.sh
$ ./echo.sh.x
Hello
$ csh
% ./echo.sh.x
% 
```

I wonder if this is a known limitation of shc approach. Here's more output with debug option turned on.

```$ ~/silcs/shc/bin/x64/shc -D -f echo.sh 
$ ./echo.sh.x 
shll=main
argc=1
argv[0]=./echo.sh.x
argv[1]=<null>
getenv(xdb3b6767f85d98dd)=<null>
shll=/bin/bash
argc=4
argv[0]=./echo.sh.x
argv[1]=-c
argv[2]=exec '/home/sunhwan/./echo.sh.x' "$@"
argv[3]=./echo.sh.x
argv[4]=<null>
shll=main
argc=1
argv[0]=/home/sunhwan/./echo.sh.x
argv[1]=<null>
getenv(xdb3b6767f85d98dd)=15797333814178322653 1
shll=/bin/bash
argc=4
argv[0]=/home/sunhwan/./echo.sh.x
argv[1]=-c
argv[2]=                                                            
argv[3]=/home/sunhwan/./echo.sh.x
argv[4]=<null>
Hello
$ csh
% ./echo.sh.x
shll=main
argc=1
argv[0]=./echo.sh.x
argv[1]=<null>
getenv(xe1b72135949ef745)=<null>
shll=/bin/bash
argc=4
argv[0]=./echo.sh.x
argv[1]=-c
argv[2]=exec '/bin/csh' "$@"
argv[3]=./echo.sh.
```

**Comment by sunhwan** [comment]
Thanks, it is fixed now.

**Comment by Patronos** [comment]
Is it fixed ?

Unfortunately this "fix" causes a regression on my system (Fedora). When running a script with "sudo", then I'll be getting this kind of errors:

-bash-4.4$ sudo toucher.sh 
toucher.sh: line 0: exec: (null): not found

I had to revert to the shc version before this "fix" to have shc behave normally again.

**Comment by neurobin** [comment]
@Patronos : can you provide a little more details?

**Comment by Patronos** [comment]
Puhhh..... Where to start....

Ok! I have an automated script, that shc compiles my bash scripts and stores them into /etc/bin (bash and sudo configs are extended to search (PATH) in this folder).

After that I use UPX (an executable packer) to pack the resulting executables to save some space (while space is not the true argument here). Please accept the fact that I do this.

One of my scripts (called toucher.sh) ran into the issue as show above, when using shc 3.9.5 (the one that has the swapped argv[0] and getenv patch applied)... By the way, shc has been compiled and stripped (strip shc) and placed into /bin/ (overwriting the old 3.9.4 one).

I ran my script again to re-create all the bash scripts again and ran into the same issue again!

Then I switched back to shc 3.9.4 and the issues has been gone. Everything worked like a charm... All scripts properly execute...

Now after you responed to me to give you more feedback I started trying to re-produce everything step by step to isolate the issue... This time the script worked. shc has produced a working version.. Then I re-created it again and figured out that sometimes the script works and executes and sometimes it returns the exec (null) issue...

Then I left the upx packing process out... So only shc processes the file... But it is quite late right now and I don't feel to continue testing today...

All I can offer so far is a small snipplet of my bash script that generates the shc file and upx crunches them. This also includes the GCC flags I've been using... Unfortunately I've not been able to reproduce the issue with this example script...

Still interesting why the toucher.sh one fails with the error above... The only thing I can say right now is: that if I go back to 3.9.4 the issues are all gone...

I will investigate more tomorrow and report back... For now have a look at the attachment...

Please rename test.txt to test.sh

[test.txt](https://github.com/neurobin/shc/files/1048930/test.txt)

**Comment by neurobin** [comment]
@Patronos  If you could catch the issue with debug mode with output like @sunhwan , that would be great. For debug, compile your script with `-D` flag added:

```
shc -Df test.sh
```

**Comment by Patronos** [comment]
Yes this did the trick! Thanks!

shc 3.9.5

-bash-4.4$ sudo toucher.sh 
shll=main
argc=1
argv[0]=toucher.sh
argv[1]=<null>
getenv(xa69d536fdacb5401)=<null>
shll=/bin/bash
argc=4
argv[0]=toucher.sh
argv[1]=-c
argv[2]=exec '(null)' "$@"
argv[3]=toucher.sh
argv[4]=<null>
toucher.sh: line 0: exec: (null): not found
-bash-4.4$ 

shc 3.9.4

-bash-4.4$ sudo toucher.sh 
shll=main
argc=1
argv[0]=toucher.sh
argv[1]=<null>
getenv(x841a7e3281de7967)=<null>
shll=/bin/bash
argc=4
argv[0]=toucher.sh
argv[1]=-c
argv[2]=exec 'toucher.sh' "$@"
argv[3]=toucher.sh
argv[4]=<null>
shll=main
argc=1
argv[0]=toucher.sh
argv[1]=<null>
getenv(x841a7e3281de7967)=9519059517793270119 1
shll=/bin/bash
argc=5
argv[0]=toucher.sh
argv[1]=--login
argv[2]=-c
argv[3]=                                                            
argv[4]=toucher.sh
argv[5]=<null>
--- fkt_xfs_db ---
actual 12944, ideal 12886, fragmentation factor 0.45%
Note, this number is largely meaningless.
Files on this filesystem average 1.00 extents per file
--- fkt_xfs_fsr ---
/media/truecrypt1 start inode=0
/media/truecrypt1 start inode=0
/media/truecrypt1 start inode=0
--- fkt_chown ---
--- fkt_setfacl ---
--- fkt_chmod ---
--- fkt_setfattr ---
--- fkt_touch ---
-bash-4.4$ 

Both scripts has been compiled using the same arguments gcc opts, shc flags, upx flags as shown in the test script above.

**Comment by neurobin** [comment]
@Patronos  Checkout the [master](https://github.com/neurobin/shc/tree/master) branch.

Also it would be helpful, if you opened a new issue with the above information. In that way, I would be able to provide clear bug fix info in the changelog.
