### ISSUE TITLE
Location Has Changed

### ISSUE THREAD

**Issue by MadTomT** [neurobin/shc#39]
Hi.

I'm running on openSuSe 42.1 within a Virtual Machine.
I compiled my script with ./shc -U -f script.sh -o script
it ran fine using: ./script

Copied the compiled script file from the VM to my PC, restored my VM from on older backup, copied the compiled script back and ran it using: ./script

I now get: 
 6w���E�^���ʮ>�MX���`location has changed! 

Any idea why I can't use the script on any of my 42.1 machines ?

Thanks

**Comment by neurobin** [comment]
Try the `-r` flag.

**Comment by MadTomT** [comment]
Thanks tried that and it seems to have resolved it :)
