### ISSUE TITLE
shc: cleanup usage of #if directive 

### ISSUE THREAD

**Issue by marcoburatto** [neurobin/shc#41]
This branch did not apply the upstream patch, https://github.com/existz/shc-3.8.9/commit/209a447e02708fdd209e1bc72c5f099125c6e443

**Comment by neurobin** [comment]
The mentioned patch is not applicable here. `#if !defined(TRACEABLE)` is not meaningful as the macro `TRACEABLE` is always defined. It's defined as `1` by default and `0` when the `-U` flag is used.
