### ISSUE TITLE
shc doesn't support expect shell

### ISSUE THREAD

**Issue by epknman** [neurobin/shc#43]
./shc -v -r -f run-command.sh
shc shll=expect
shc Unknown shell (expect): specify [-i][-x][-l]
./shc: Success

**Comment by nixgeekk** [comment]
Will shc support expect in the future?

**Comment by neurobin** [comment]
no plans for now..

**Comment by intika** [comment]
Can you try with the new flag H and let me know

**Comment by chenyukang** [comment]
I need to support expect, so implement this in Rust, 
https://github.com/chenyukang/rshc
