### ISSUE TITLE
Binary doesn't understand kernel capabilities

### ISSUE THREAD

**Issue by q2dg** [neurobin/shc#45]
Hello.
I've this simple script called "spy.sh":
   #!/bin/bash
   ncat -l -p 80 &

And after executing shc -f spy.sh -o spy.exe , if I do...:
   setcap cap_net_bind_service=eip spy.exe

...I get this error: "Ncat: bind to :::80: Permission denied. QUITTING."

I understand this error is given by Ncat, which it hasn't any assigned capability but...should it happen like this? Isn't my binary independent from others?

Thanks!

**Comment by neurobin** [comment]
nope, binary is still dependent on your shell, the command `ncat -l -p 80 &` is run with bash as it would if you simply ran the script.

**Comment by q2dg** [comment]
Ok. Thanks a lot.
I close this issue, then.
Cheers!
