### ISSUE TITLE
Busybox/initrd issue

### ISSUE THREAD

**Issue by marcoburatto** [neurobin/shc#5]
shc files are not compatible with Busybox and so one cannot use it in order to build an initrd-compatible executable.

Found this patch over the Internet (credits to its coder) and it works great. 
https://onedrive.live.com/prev?cid=18a41d08a9f3c543&id=18A41D08A9F3C543!231&authkey=!AJQ6Iah_5D3WJ60&v=TextFileEditor

Tested on Debian 7 initrd.

**Comment by neurobin** [comment]
I have applied the patch, and pushed a new commit, can you please check it?

**Comment by marcoburatto** [comment]
Thanks for replying.
I think this broke 32 bit compatibility.








*# shc-su: /usr/bin/shc: cannot execute binary file# shc-oldshc parse(-f):
No source file specifiedshc Usage: shc [-e date] [-m addr] [-i iopt] [-x
cmnd] [-l lopt] [-o outfile] [-rvDUCAh] -f script*
(I moved file into /usr/bin after installation)







*# file /usr/bin/shc/usr/bin/shc: ELF 64-bit LSB executable, x86-64,
version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux
2.6.24, stripped# file /usr/bin/shc-old/usr/bin/shc-old: ELF 32-bit LSB
executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared
libs), for GNU/Linux 2.6.26,
BuildID[sha1]=0x38b8fc6f624afefb401d603d8f2519d7b3f86a51, stripped*



~
ing. Marco Buratto

<https://www.linkedin.com/in/mburatto>
CTO & developer, *fbplayer.com <http://fbplayer.com>*
Senior system architect,
* LumIT S.p.A.*Linux-based operating systems creator, *binaryemotions.com
<http://binaryemotions.com>*

The next generation operating system on a key, *secure-k.com
<http://secure-k.com>*
Meet local people who will assist you in your next trip, *triptourist.net
<http://triptourist.net>*


2015-08-21 12:32 GMT+02:00 Jahidul Hamid <notifications@github.com>:

**Comment by neurobin** [comment]
Something is wrong. My makefile should install `shc` to `/usr/local/bin` not `/usr/bin`. And the binary in the `main` directory is compiled for 64 bit and it's outdated too. If you have installed it with `make` and `make install` it should go to `/usr/local/bin`. Can you try running directly `/usr/local/bin/shc` ?

**Comment by marcoburatto** [comment]
Yes it's true; as I wrote, I moved the file after installation, but if I try make it running from /usr/local/bin, result is the same.

root@debian:/tmp# wget https://github.com/neurobin/shc/archive/release.zip
--2015-08-24 18:18:12--  https://github.com/neurobin/shc/archive/release.zip
Risoluzione di github.com (github.com)... 192.30.252.128
Connessione a github.com (github.com)|192.30.252.128|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 302 Found
Posizione: https://codeload.github.com/neurobin/shc/zip/release [segue]
--2015-08-24 18:18:13--  https://codeload.github.com/neurobin/shc/zip/release
Risoluzione di codeload.github.com (codeload.github.com)... 192.30.252.145
Connessione a codeload.github.com (codeload.github.com)|192.30.252.145|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: non specificato [application/zip]
Salvataggio in: "release.zip"

    [  <=>                                                                                                                                      ] 45.541       208K/s   in 0,2s    

2015-08-24 18:18:17 (208 KB/s) - "release.zip" salvato [45541]

root@debian:/tmp# unzip release.zip 
Archive:  release.zip
0dc3ab7dd1d24252c1068ccf2d956c8265b2d4f1
   creating: shc-release/
  inflating: shc-release/CHANGES     
  inflating: shc-release/LICENSE     
  inflating: shc-release/README.md   
  inflating: shc-release/install     
   creating: shc-release/main/
  inflating: shc-release/main/makefile  
  inflating: shc-release/main/shc    
  inflating: shc-release/main/shc.1  
  inflating: shc-release/main/shc.c  
  inflating: shc-release/main/shc.html  
   creating: shc-release/test/
  inflating: shc-release/test/match  
  inflating: shc-release/test/pru.sh  
  inflating: shc-release/test/test.bash  
 extracting: shc-release/test/test.csh  
  inflating: shc-release/test/test.ksh  
root@debian:/tmp# cd shc-release/
root@debian:/tmp/shc-release# ls
CHANGES  install  LICENSE  main  README.md  test
root@debian:/tmp/shc-release# ./install 
Starting installation....
***	Do you want to probe shc with a test script?: 
***	Please try...	make test
***	Installing shc and shc.1 on /usr/local
install -c -s shc /usr/local/bin/
mkdir -p /usr/local/man/man1/
install -c -m 644 shc.1 /usr/local/man/man1/
Finished successfully
Enter 'man shc' for manual
root@debian:/tmp/shc-release# ls -l /usr/local/bin/shc 
-rwxr-xr-x 1 root staff 31576 ago 24 18:18 /usr/local/bin/shc
root@debian:/tmp/shc-release# file /usr/local/bin/shc 
/usr/local/bin/shc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, stripped
root@debian:/tmp/shc-release# /usr/local/bin/shc 
-su: /usr/local/bin/shc: cannot execute binary file

**Comment by neurobin** [comment]
One final question, your system 64bit or 32bit?

**Comment by marcoburatto** [comment]
It's a Debian 7, 32bit.

**Comment by neurobin** [comment]
I don't get it how a 32 bit system is producing a 64bit binary,  may be a problem with my makefile. Anyway, can you check it by compiling with `gcc` with `-m32` flag:
`gcc -m32 shc.c -o shc`
It will produce a 32 bit binary which should run without any problem:
`./shc`

**Comment by neurobin** [comment]
I have added compiled 32 bit binary. You can check it that works.

**Comment by marcoburatto** [comment]
Now it is running perfectly on my 32 bit system and the "-B" switch is producing Busybox compatible binaries.
Thanks for your work.
Ciao :)

**Comment by neurobin** [comment]
great, thanks for your time...
