### ISSUE TITLE
Would an executable produced with SHC fall under GPL?

### ISSUE THREAD

**Issue by TJesionowski** [neurobin/shc#50]
SHC is licensed under GPL3. Technically, shell scripts obfuscted with SHC are embedded into SHC C code and then compiled.  

How does SHC avoid putting shell scripts under GPL, seeing as how the GPL would be antithetical to the purpose of SHC, which is to avoid the necessity of distributing the source code of programs written in bash?

**Comment by neurobin** [comment]
produced binary should not fall under GPL.
