### ISSUE TITLE
Trying to compile and run my script results in garbage output

### ISSUE THREAD

**Issue by aniruddha-a** [neurobin/shc#6]
Hello,

I tried `shc` on some small scripts, and once they worked fine, I tried to compile a slightly larger one
(~`200` line `bash` script). When tried to run, I see garbage characters!

    $ ./script.sh.x args
    ./script.sh.x: ��Oy�(��ʛ��W__��@�)

The reason I wanted to use `shc` was - I had to run the script with privileges, so instead of making
the script itself a SUID executable, I wanted to compile it and then make it an SUID program!

**Comment by neurobin** [comment]
The size of the script is limited by the `_SC_ARG_MAX system configuration parameter`. It seems your script crossed this limit.
