### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by suntong** [neurobin/shc#79]
Hi @neurobin, 

I'm building the new Debian package and have found 2 typos:

shc processs process
shc.1 Unfortunatelly Unfortunately

I'm fixing it now. 
Hope the PR is accepted.

**Comment by suntong** [comment]
Hi @neurobin,

Please push a new tag as the `gbp import-orig --uscan` on my end is not picking up the new changes (because of no new tag), yet `lintian` is complaining about those spelling errors. 

You might want to tag it as official Debian release. 

THX!

**Comment by neurobin** [comment]
new release 4.0.2

**Comment by suntong** [comment]
THANKS A LOT @neurobin !
