### ISSUE TITLE
shc compiled script doesn't accept arguments 

### ISSUE THREAD

**Issue by leondavi** [neurobin/shc#81]
I wrote a script that gets arguments when is called from shell. 
The script performs echo to $1 to show the input argument and works fine. 
However, when compiling it using shc the binary script doesn't receive the arguments
from the shell and therefore prints nothing.  

The binary script was generated by running gcc on shc c-file output. 
shc was generated with the following flags: shc -H -f script.sh
Example: 
```./script.sh a ```   prints a <n>
```./script_shc_bin a ```   doesn't print

**Comment by neurobin** [comment]
https://github.com/neurobin/shc#the-hardening-flag--h

**Comment by leondavi** [comment]
Thanks.
