### ISSUE TITLE
4.0.2:  wrong version in configure.ac

### ISSUE THREAD

**Issue by eribertomota** [neurobin/shc#88]
Dear maintainer,

The configure.ac for 4.0.2 version says: "AC_INIT([shc], [4.0.1], [http://github.com/neurobin/shc/issues])". It will reflect in several files, as configure and shc.

Please, use a checklist to release a new version. There is an example here[1].

[1] https://github.com/resurrecting-open-source-projects/scrot/blob/master/doc/UPDATE-CHECK

Regards,

Eriberto

**Comment by eribertomota** [comment]
The following file also wrong:

src/shc.c:static const char version[] = "Version 4.0.1";

**Comment by eribertomota** [comment]
Please, be polite. Do not close an issue without pointing a fix or without explain the case.

**Comment by neurobin** [comment]
I think closing means it's resolved. Sorry if I hurt you making assumptions.

By the way, there is a new 4.0.2 version available now, it's a bit different from previous one and I think it's how it's supposed to be. There is the latest 4.0.3 available now with removing the experimental `-s` flag (by @intika).

**Comment by eribertomota** [comment]
Thanks a lot for your clarification.

Regards,

Eriberto


Em sex, 5 de jul de 2019 às 05:14, Md Jahidul Hamid <
notifications@github.com> escreveu:
